### ISSUE TITLE
[rancid 3.4.1]: no matching cipher found

### ISSUE THREAD

**Issue by joschi99** [joschi99/Osiris#48]
Rancid 3.4.1 in combination with a Dell N1524 switch reports on login using dllogin the error:

```
[rancid@osiris2` bin]$ ./dllogin 192.168.253.203
192.168.253.203
spawn ssh -c 3des -x -l admin 192.168.253.203
no matching cipher found: client 3des-cbc server aes128-ctr,aes192-ctr,aes256-ctr,arcfour,arcfour128,arcfour256,chacha20-poly1305@openssh.com,

Error: Couldn't login: 192.168.253.203
```

**Comment by joschi99** [comment]
Solution

add the cipher type in the clogin file

`add cyphertype <devicename> aes192-ctr`

**Comment by longzhang-barchart** [comment]
Thanks, it works. Do you know what is the problem?

**Comment by rtmabnet** [comment]
I'm running rancid 3.9 and this didn't work:

> add the cipher type in the .cloginrc file
> 
> add cyphertype <devicename> aes192-ctr

Bit of a bodge but this worked for me:

Edit the line:

if { "$cyphertype" == "" } { set cyphertype "3des" }

in '/usr/local/sbin/clogin'

to 

if { "$cyphertype" == "" } { set cyphertype "aes256-ctr" }
